openapi: 3.0.1
info:
  title: PubNub Push Notifications || APN & GCM APIs
  description: This is the place where you can find all PubNub Channel Groups Endpoint APIs
  termsOfService: http://pubnub.com/terms/
  contact:
    email: support@pubnub.com
  version: 0.0.1
servers:
- url: https://ps.pndsn.com
tags:
- name: Push Notifications
  description: PubNub push notification service supports apple, google and microsoft push notification service plateforms.
paths:
  /v2/push/sub-key/{sub_key}/device-apns2/{device-apns2}:
    get:
      tags:
      - Push Notifications
      summary: Managing device registrations (APNS HTTP/2)
      description: 'Add and remove channels in a single API call'
      parameters:
      - $ref: '#/components/parameters/SubKeyPathParam'
      - $ref: '#/components/parameters/DeviceApns2PathParam'
      - $ref: '#/components/parameters/UuidQueryParam'
      - $ref: '#/components/parameters/AuthQueryParam'
      - $ref: '#/components/parameters/ListQueryParam'
      - $ref: '#/components/parameters/AddQueryParam'
      - $ref: '#/components/parameters/RemoveQueryParam'
      - $ref: '#/components/parameters/EnvironmentQueryParam'
      - $ref: '#/components/parameters/TopicQueryParam'
      responses:
        '200':
          description: Success

  /v2/push/sub-key/{sub_key}/device-apns2/{device-apns2}/remove:
    get:
      tags:
      - Push Notifications
      summary: Remove a device from a channel
      description: Bulk modification of a device, allowing for removal of all registered channels at once, for a given device, without specifying all of the channels.
      parameters:
      - $ref: '#/components/parameters/SubKeyPathParam'
      - $ref: '#/components/parameters/DeviceApns2PathParam'
      - $ref: '#/components/parameters/UuidQueryParam'
      - $ref: '#/components/parameters/AuthQueryParam'
      - $ref: '#/components/parameters/AddQueryParam'
      - $ref: '#/components/parameters/RemoveQueryParam'
      - $ref: '#/components/parameters/EnvironmentQueryParam'
      - $ref: '#/components/parameters/TopicQueryParam'
      responses:
        '200':
          description: Success
  /v1/push/sub-key/{sub_key}/devices/{push_token}:
    get:
      tags:
      - Push Notifications
      summary: Listing/Adding/Removing registrations for device
      description: List/Add/Remove registrations for device
      parameters:
      - $ref: '#/components/parameters/SubKeyPathParam'
      - $ref: '#/components/parameters/PushTokenPathParam'
      - $ref: '#/components/parameters/TypeQueryParam'
      - $ref: '#/components/parameters/UuidQueryParam'
      responses:
        '200':
          description: OK  
          content:
            application/json:
             schema:
              $ref: '#/components/schemas/ManageChannelDeviceResponse'
             
  /v1/push/sub-key/{sub_key}/devices/{push_token}/remove:
    get:
      tags:
      - Push Notifications
      summary: Removing a device
      description: Remove all registrations for a device
      parameters:
      - $ref: '#/components/parameters/SubKeyPathParam'
      - $ref: '#/components/parameters/PushTokenPathParam'
      - $ref: '#/components/parameters/TypeQueryParam'
      - $ref: '#/components/parameters/UuidQueryParam'        
      responses:
        '200':
          description: OK  
          content:
            application/json:
             schema:
              $ref: '#/components/schemas/ManageChannelDeviceResponse'

components:
  parameters:
    SubKeyPathParam:
      name: sub_key
      in: path
      description: The subscriber key.
      required: true
      schema:
        type: string
        example: sub-c-406fe670-ff0a-11e8-a860-92908bb92f21
    DeviceApns2PathParam:
      name: device-apns2
      in: path
      description: the id/token of the device
      required: true
      schema:
        type: string
      example: A332C23D
    UuidQueryParam:
      name: uuid
      in: query
      description: UUID of the client
      required: true
      schema:
        type: string
      example: db9c5e39-7c95-40f5-8d71-125765b6f561        
    AuthQueryParam:
      name: auth
      in: query
      description: PAM authorization key
      required: true
      schema:
        type: string
      example: 385dfa9c-6a16-4145-aaf9-043f0060c7d3
    ListQueryParam:
      name: list
      in: query
      description: indicates list of channels to which the device should be added, for push registration (mulitple channels are also supported by comma delimited (ch1,ch2,ch3) will add three channels)
      required: true
      schema:
        type: string
      example: channel1     
    AddQueryParam:
      name: add
      in: query
      description: indicates list of channels to which the device should be added, for push registration (mulitple channels are also supported by comma delimited (ch1,ch2,ch3) will add three channels)
      required: true
      schema:
        type: string
      example: channel1
    RemoveQueryParam:
      name: remove
      in: query
      description: name of the channel for which the device will no longer recieve push notifications (mulitple channels are also supported by commad delimited (ch1,ch2,ch3) will remove three channels)
      required: true
      schema:
        type: string
      example: channel1 
    EnvironmentQueryParam:
      name: environment
      in: query
      description: either "development" or "production", denoting the environment of the mobile application
      required: true
      schema:
        type: string
      example: development
    TopicQueryParam:
      name: topic
      in: query
      description: bundle id of the mobile application
      required: true
      schema:
        type: string
      example: com.my.app.Application  
    PushTokenPathParam:
      name: push_token
      in: path
      description: the push token of the device
      required: true
      schema:
        type: string
      example: A332C23D    
    TypeQueryParam:
      name: type
      in: query
      description: indicates the backend to use (apns for apple, gcm for google, mpns for microsoft)
      required: true
      schema:
        type: string
        enum: [apns, gcm, mpns]
      example: apns    
      
  schemas:
    ManageChannelDeviceResponse:
      type: array
      items:
        oneOf:
         - type: integer                
         - type: string
      example: [1, "Modified Channels"]